# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 053cbce5bef55a2d88457c4e6821a7d31cb0a0aff33360d0473e1bc254ed30d9ffda6c5cdbf62343348c792cc4076da90498cd2f32e46a46c6ba137d81c600df

test:
  secret_key_base: 7c5c9b6bd2dd10827debbd47d741eb16ca8c1806ae047ffa568150cf8c2b2ba78f01f92a2f45c334b1944b7b7953359548ab9ccd7b4325d54bc83a16e4779a87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
